app/apps/audit/urls.py
from django.urls import path

from apps.audit.views import (
  RequestLogListView, 
)

app_name = 'audit'

urlpatterns = [
    path('logs/', RequestLogListView.as_view(), name='request_logs'),
]

app/apps/base/urls.py
from django.urls import path

from apps.base.views import (
  settings_view, 
)

app_name = 'base'

urlpatterns = [
    path('settings/', settings_view, name='settings'),
]

app/apps/cv/urls.py
from rest_framework.routers import DefaultRouter
from django.urls import path, include

from apps.cv.views import (
  IndexView, 
  CvDetailView,
  CvViewSet
)

app_name = 'cv'

router = DefaultRouter()
router.register('cv', CvViewSet, basename='cv')


urlpatterns = [
    path('api/v1/', include(router.urls)),
    path('', IndexView.as_view(), name='index'),
    path('cv-detail/<uuid:pk>/', CvDetailView.as_view(), name='cv-detail'),
]

app/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.cv.urls')),
    path('', include('apps.audit.urls')),
    path('', include('apps.base.urls'))
]

app/apps/audit/models.py
from django.db import models
from apps.base.models import BaseModel
from django.contrib.auth.models import User


class RequestLog(BaseModel):
  http_method = models.CharField(max_length=32)
  status = models.IntegerField(null=True)
  path = models.CharField(max_length=128)
  ip_address = models.CharField(max_length=128)
  duration = models.CharField(null=True)
  user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

  class Meta:
    verbose_name = 'Audit'
    verbose_name_plural = 'Audits'
    db_table = 'request_logs'

  def __str__(self) -> str:
    return f"{self.http_method} - {self.status}"


  

app/apps/base/models.py
from django.db import models



class BaseModel(models.Model):

  '''

  Base model that using for additional information about objects.

    is_active: Shows whether the object is still relevant instead of being deleted.
    created_at: Shows when the object was delete.
    updated_at: Shows when the object was updated.

  '''
  
  is_active = models.BooleanField(default=True, verbose_name='IsActive', help_text='Shows whether the object is still relevant')
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True) 

  class Meta:
    abstract = True
    ordering = '-created_at'

  def update(self, **kwargs):
    for attr, value in kwargs.items():
        setattr(self, attr, value)
    self.save()

app/apps/cv/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User

from apps.base.models import BaseModel


class Header(BaseModel):

  '''
  
  Header model.

    related models:
      CV OneToOne Header
  
  '''
  
  # avatar = ""
  full_name = models.CharField(max_length=128, blank=True)
  position = models.CharField(max_length=128, blank=True)
  linkedin_url = models.URLField(max_length=255, blank=True)
  
  class Meta:
    db_table = "header"
  
  def __str__(self) -> str:
    return self.full_name


class CV(BaseModel):
  
  '''
  
  CV model.

    filename: name of the CV file. The user can enter it manually, or it will be generated automatically.
    header: header of cv page.
    user: authorized user owner of cv creation.
    
    related models:
      BodySection ManyToOne CV 
      
  '''
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  filename = models.CharField(max_length=48, default="", blank=True, verbose_name='File name')
  header = models.OneToOneField(Header, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Header', help_text='Header of cv page')

  def __str__(self) -> str:
    return self.filename
  
  class Meta:
    db_table = "cv"
    ordering = ['-updated_at']
  


class BodySection(BaseModel):

  '''
  
  Model BodySection.
    
    name: name of section.
    description: description of section.
  
  '''
  
  # icon = ''
  cv = models.ForeignKey(CV, on_delete=models.CASCADE, null=True, blank=True, related_name='body_sections')
  name = models.CharField(max_length=32)
  description = models.TextField()

  def __str__(self) -> str:
    return self.name
  
  class Meta:
    db_table = "body_section"
    ordering = ['created_at']

  # def update(self, **kwargs):
  #   ...

app/backend/apps/audit/models.py
from django.db import models
from apps.base.models import BaseModel
from django.contrib.auth.models import User


class RequestLog(BaseModel):
  http_method = models.CharField(max_length=32)
  status = models.IntegerField(null=True)
  path = models.CharField(max_length=128)
  ip_address = models.CharField(max_length=128)
  duration = models.CharField(max_length=128, null=True)
  user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

  class Meta:
    verbose_name = 'Audit'
    verbose_name_plural = 'Audits'
    db_table = 'request_logs'

  def __str__(self) -> str:
    return f"{self.http_method} - {self.status}"


  

app/apps/audit/views.py
from django.shortcuts import render
from django.views import generic

from apps.audit.models import RequestLog


class RequestLogListView(generic.ListView):
  model = RequestLog
  queryset = RequestLog.objects.all().order_by('-id')
  template_name = "request_logs/list.html"
  paginate_by = 10

app/apps/base/views.py
from django.shortcuts import render


def settings_view(request):
  template_name = 'settings/main.html'
  return render(request=request, template_name=template_name)

app/apps/cv/views.py
from rest_framework.views import APIView
from rest_framework import status, viewsets
from django.views import generic

from apps.cv.models import CV
from apps.cv.serializers import CvSerializer


class IndexView(generic.ListView):
  queryset = CV.objects.select_related('header').prefetch_related('body_sections').all()
  template_name = 'index/index.html'      


class CvDetailView(generic.DetailView):
  model = CV
  template_name = 'cv_detail/detail.html'


class CvViewSet(viewsets.ModelViewSet):
  model = CV
  queryset = CV.objects.select_related('header').prefetch_related('body_sections').all()
  serializer_class = CvSerializer

app/templates/cv_detail/detail.html
{% extends 'layouts/base.html' %}

{% block stylesheets %}

<style>

body {
  font-family: 'Inter', sans-serif;
}

.cv-detail-container {
  display: block;
  width: 70%;
  margin: 0 auto;
  height: 1000px;
}

 .cv-card {
  width: 100%; 
  box-sizing: border-box; 
  height: 100%;
  

  border-radius: 5px;
  box-shadow: 0 8px 20px rgba(0,0,0,0.2);
  
}

.cv-header {
  display: flex;

  width: 100%;
  background-color: #84abef;
  object-fit: cover;
  margin-right: 20px;

  align-items: center;
  height: 180px; 

  border-top-left-radius: var(--border-radius);
  border-top-right-radius: var(--border-radius);
  padding: 20px;
  box-sizing: border-box;
}

.header-detail-info {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
}

.header-component {
  color: white;
  font-weight: bold;
  padding: 10px;
}


.header-avatar img {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  object-fit: cover;
  border: 3px solid white;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  transition: var(--transition);
}


.cv-body {
  border: none !important;
  padding: 24px;
  font-size: 15px;
  height: 100% auto;
  margin: 0;
  background-color: transparent;
}

.cv-section {
  margin-top: 15px;
}


</style>

{% endblock stylesheets %}


{% block content %}
<div class="cv-detail-container">
  <div class="cv-card">
    {% include 'cv_detail/cv.html' %}
  </div>
</div>
{% endblock content %}


{% block javascripts %}


<script>

function HtmlToPdf() {
  const cv_card = document.getElementById('id_cv_card')
  const options = getCvPdfOptions()

  html2pdf().set(options).from(cv_card).save();
}

function getCvPdfOptions() {
    const options = {
      filename: 'my-document.pdf',
      margin: 1,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'in', format: 'A4', orientation: 'portrait' },
      margin: [0, 0, 0, 0]
    };

    return options
}

</script>

{% endblock javascripts %}

app/templates/includes/wrapper.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container">
      
      <div class="d-flex">
        <a 
          href="{% url 'cv:index' %}"
          class="navbar-brand" 
        >
          <div class="sidebar-icon transition">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-grid-3x3-gap-fill me-2" viewBox="0 0 16 16">
              <path d="M1 2a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1zM1 7a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1zM1 12a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1zm5 0a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1z"/>
            </svg>
            Home
          </div>
        </a>

        <a 
          href="{% url 'audit:request_logs' %}"
          class="navbar-brand" 
        >
          <div class="sidebar-icon transition">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-gear" viewBox="0 0 16 16">
              <path d="M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4m.256 7a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1zm3.63-4.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382zM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0"/>
            </svg>
            <span class="ms-1">
              logs
            </span>
            
          </div>
        </a>

        <a 
          href="{% url 'base:settings' %}"
          class="navbar-brand" 
        >
          <div class="sidebar-icon transition">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear-wide-connected" viewBox="0 0 16 16">
              <path d="M7.068.727c.243-.97 1.62-.97 1.864 0l.071.286a.96.96 0 0 0 1.622.434l.205-.211c.695-.719 1.888-.03 1.613.931l-.08.284a.96.96 0 0 0 1.187 1.187l.283-.081c.96-.275 1.65.918.931 1.613l-.211.205a.96.96 0 0 0 .434 1.622l.286.071c.97.243.97 1.62 0 1.864l-.286.071a.96.96 0 0 0-.434 1.622l.211.205c.719.695.03 1.888-.931 1.613l-.284-.08a.96.96 0 0 0-1.187 1.187l.081.283c.275.96-.918 1.65-1.613.931l-.205-.211a.96.96 0 0 0-1.622.434l-.071.286c-.243.97-1.62.97-1.864 0l-.071-.286a.96.96 0 0 0-1.622-.434l-.205.211c-.695.719-1.888.03-1.613-.931l.08-.284a.96.96 0 0 0-1.186-1.187l-.284.081c-.96.275-1.65-.918-.931-1.613l.211-.205a.96.96 0 0 0-.434-1.622l-.286-.071c-.97-.243-.97-1.62 0-1.864l.286-.071a.96.96 0 0 0 .434-1.622l-.211-.205c-.719-.695-.03-1.888.931-1.613l.284.08a.96.96 0 0 0 1.187-1.186l-.081-.284c-.275-.96.918-1.65 1.613-.931l.205.211a.96.96 0 0 0 1.622-.434zM12.973 8.5H8.25l-2.834 3.779A4.998 4.998 0 0 0 12.973 8.5m0-1a4.998 4.998 0 0 0-7.557-3.779l2.834 3.78zM5.048 3.967l-.087.065zm-.431.355A4.98 4.98 0 0 0 3.002 8c0 1.455.622 2.765 1.615 3.678L7.375 8zm.344 7.646.087.065z"/>
            </svg>
            <span class="ms-1">
              settings
            </span>
            
          </div>
        </a>
        
      </div>


      {% if 'cv-detail' in request.path %}
        
          <div class="sidebar-icon transition p-3" style="background-color: #200e32; border: none; gap: 5px;" onclick="HtmlToPdf()">

            <div style="color: white">
              Download
            </div>

            <svg style="color: white;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
              <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
              <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
            </svg>   
          </div>
       
      {% endif %}
    
    </div>
  </nav>

app/templates/index/index.html
{% extends 'layouts/base.html' %}

{% block stylesheets %}
<style>
  .cv-container {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
    gap: 10px;
    margin-top: 20px;
  }

  .cv-detail-link {
    text-decoration: none;
  }

  .cv-card {
    border: 1px solid !important;
    background: #fff;

    border: 1px solid #ddd;
    border-radius: 12px;
    padding: 20px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.05);
    transition: transform 0.2s ease, box-shadow 0.2s ease;
    cursor: pointer;
    width: 250px;
    height: 320px;
  }

  .cv-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 6px 12px rgba(0,0,0,0.1);
  }

  .cv-title {
    font-size: 18px;
    font-weight: 600;
    margin-bottom: 10px;
    text-align: center;
  }

  .cv-meta {
    font-size: 14px;
    color: #666;
  }
</style>
{% endblock stylesheets %}

{% block content %}
<div class="cv-container">
  {% for cv in object_list %}
  <a class="cv-detail-link" href="{% url 'cv:cv-detail' cv.id %}">
    <div class="cv-card">
      <div class="cv-title">{{ cv.filename }}</div>
      <div class="cv-meta text-center">{{ cv.header.full_name }}</div>


      <div class="cv-meta mt-3">{{ cv.header.position }}</div>
      <div class="cv-meta">{{ cv.header.linkedin_url }}</div>
      <div class="cv-meta">Created: {{ cv.created_at|date:"Y-m-d" }}</div>
    </div>
  </a>
  {% empty %}
    <p>No CVs found.</p>
  {% endfor %}
</div>
{% endblock content %}

app/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap5 --> 
  <link 
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"
  >
  <script
   src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
  </script>
  <!----------------> 

  <!-- html2pdf -->
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.2/html2pdf.bundle.min.js"
    integrity="sha512-MpDFIChbcXl2QgipQrt1VcPHMldRILetapBl5MPCA9Y8r7qvlwx1/Mc9hNTzY+kS5kX6PdoDq41ws1HiVNLdZA=="
    crossorigin="anonymous"
    referrerpolicy="no-referrer">
  </script>
  <!---------------->

  <link rel="stylesheet" href="{% static 'styles/main.css' %}?v={{ STATIC_VERSION }}">
  

  {% block title %}{% endblock title %}

  {% block stylesheets %} 
  
  <style>

  </style>
  
  {% endblock stylesheets %}
</head>

<body class="container">

  {% include 'includes/wrapper.html' %}

  {% block content %}
  {% endblock content %}
</body>
</html>

{% block javascripts %}{% endblock javascripts %}

app/templates/request_logs/list.html
{% extends 'layouts/base.html' %}

{% block stylesheets %}
<style>
.table-container {
  width: 100%;
  overflow-x: auto;
  margin-top: 20px;
  overflow: hidden;
  padding: 10px;
  
  border-radius: 5px;
  box-shadow: 0 8px 20px rgba(0,0,0,0.2);
}

table {
  width: 100%;
  border: 1px solid ;
  height: 800px;
  
  border-collapse: collapse;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
}

thead {
  background-color: #84abef;
  color: white;
}

th, td {
  text-align: left;
  padding: 12px 15px;
  border-bottom: 1px solid #ddd;
}

tbody tr:hover {
  background-color: #f1f1f1;
  transition: all 0.2s ease;
  border-radius: 5px;
  box-shadow: 0 8px 20px rgba(0,0,0,0.2);
}

th {
  font-weight: 600;
}

tbody tr:last-child td {
  border-bottom: none;
}

@media (max-width: 768px) {
  table, thead, tbody, th, td, tr {
    display: block;
  }

  thead tr {
    display: none;
  }

  tr {
    margin-bottom: 15px;
    border: 1px solid #ddd;
    border-radius: 12px;
    padding: 10px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.05);
    background-color: #fff;
  }

  td {
    text-align: right;
    padding-left: 50%;
    position: relative;
  }

  td::before {
    content: attr(data-label);
    position: absolute;
    left: 15px;
    width: 45%;
    padding-left: 10px;
    font-weight: 600;
    text-align: left;
  }
}
</style>
{% endblock stylesheets %}

{% block content %}
<div class="table-container">
  <table>
    <thead>
      <tr>
        <th>HTTP method</th>
        <th>Status code</th>
        <th>Path</th>
        <th>IP address</th>
        <th>Request duration</th>
        <th>Timestamp</th>
        <th>User</th>
      </tr>
    </thead>
    <tbody>
      {% for log in object_list %}
        <tr>
          <td>{{ log.http_method }}</td>
          <td>{{ log.status }}</td>
          <td>{{ log.path }}</td>
          <td>{{ log.ip_address }}</td>
          <td>{{ log.duration|default_if_none:''|slice:":8" }}</td>
          <td>{{ log.created_at }}</td>
          <td>{{ log.user|default_if_none:'Anonymous' }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock content %}

app/templates/settings/main.html
{% extends 'layouts/base.html' %}

{% block stylesheets %}
<style>

  .settings-container {
    max-width: 1200px;
    margin: 40px auto;
    padding: 0 20px;
  }

  h1 {
    font-size: 2rem;
    text-align: center;
    margin-bottom: 30px;
    color: #5d87d0;
  }

  .card {
    background-color: #fff;
    border-radius: 12px;
    box-shadow: 0 4px 16px rgba(0,0,0,0.08);
    padding: 20px;
    margin-bottom: 20px;
    transition: transform 0.2s ease, box-shadow 0.2s ease;
  }

  .card:hover {
    box-shadow: 0 8px 24px rgba(0,0,0,0.2);
  }

  .card-title {
    font-size: 1.25rem;
    font-weight: 600;
    margin-bottom: 10px;
    color: #5d87d0;
  }

  .card-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 20px;
  }

</style>
{% endblock stylesheets %}

{% block content %}
<div class="settings-container">
  <h1>Settings</h1>
  
  <div class="card-grid">
    <div class="card">
      <div class="card-title">Debug: {{ DEBUG }}</div>
    </div>

    <div class="card">
     <div class="card-title">LANGUAGE_CODE: {{ LANGUAGE_CODE }}</div>
    </div>

    <div class="card">
     <div class="card-title">TIME_ZONE: {{ TIME_ZONE }}</div>
    </div>

    <div class="card">
     <div class="card-title">USE_I18N: {{ USE_I18N }}</div>
    </div>
    
    <div class="card">
     <div class="card-title">USE_TZ: {{ USE_TZ }}</div>
    </div>

  </div>
</div>
{% endblock content %}